name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      # Install premake on the system
      - name: Setup premake ğŸ”§
        uses: abel0b/setup-premake@v1
      - name: Create project files ğŸš¦
        run: premake5 gmake2
      
      # Install Dependencies for OpenGL
      - name: Install dependencies for OpenGL âŒ›
        run: sudo apt update && sudo apt install libglu1-mesa-dev freeglut3-dev mesa-common-dev

      # Build test to build the project
      - name: Build debug ğŸš€
        run: make config=debug
      - name: Build release â˜„ï¸
        run: make config=release
